version: "1"
services:
  db:
    image:  mysql
    restart: always 
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: invoicesApp
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
     
  # test-db:
  #   image:  postgres
  #   restart: always 
  #   ports:
  #     - "3306:3306"
  #   environment:
  #      MYSQL_ROOT_PASSWORD: admin